import type { Metadata } from "next";
import { Lexend, Elsie, Kode_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import NavigationBar from "@/components/navigation-bar";

const elsie = Elsie({
  subsets: ["latin"],
  weight: ["400", "900"],
  display: "swap",
  variable: "--font-elsie",
});

const lexend = Lexend({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  variable: "--font-lexend",
});

const kodeMono = Kode_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-kode-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const symbols = localFont({
  preload: true,
  src: [
    {
      path: "../../public/fonts/symbols.woff2",
      style: "normal",
    },
  ],
  variable: "--symbols-rounded",
  display: "block",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${elsie.variable} ${lexend.variable} ${kodeMono.variable} ${symbols.variable} scroll-smooth`}
      suppressHydrationWarning
    >
      <body
        className={
          "bg-background text-foreground font-sans font-light antialiased flex min-h-screen flex-col p-4"
        }
      >
        <NavigationBar />
        <main className="flex flex-col mx-auto max-w-2xl w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
